name: Block Sensitive File Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-sensitive-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: files
        run: |
          echo "FILES=$(git diff --name-only origin/main...HEAD | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Check for sensitive file changes
        run: |
          echo "Changed files: $FILES"
          if echo "$FILES" | grep -E '\.github/CODEOWNERS|\.env|\.github/workflows/'; then
            echo "::error title=Sensitive File Modified::One or more protected files were modified. Only @Nerpi99 should change these."
            exit 1
          fi
